[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/"]

## connect chainlink contract to brownie contract

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

## Set ffi= true, foundry devops 
ffi = true   ## foundry will run  commands directly on my machine